Foodex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('orders.urls')),
    path('', include('users.urls')),
]

dashboard/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from dashboard.views import (
    Homepage, ItemView,
    Menu, About, CartView, WatchlistView, OrdertableView, paymentdetails
)

app_name = 'dashboard'
# list of urls for dashborad
urlpatterns = [
    path('', Homepage.as_view(), name='home'),
    path('menu', Menu.as_view(), name='menu'),
    path('about', About.as_view(), name='about'),
    path('cart', login_required(CartView.as_view(), login_url='users:login'), name='cart'),
    path('watchlist', login_required(WatchlistView.as_view(), login_url='users:login'), name='watchlist'),
    path('ordertable', login_required(OrdertableView.as_view(), login_url='users:login'), name='ordertable'),
    re_path('^item/(?P<id>[0-9]+)/$', login_required(ItemView.as_view(), login_url='users:login'), name='item'),
    re_path('^paymentdetails/(?P<id>[0-9]+)/$', paymentdetails, name='paymentdetails'),
]

orders/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from orders.views import (
    OrdersView, OrderItemView, PaymentView,
    removeorder, reviewitem
)
app_name = 'orders'
# list of urls for dashborad
urlpatterns = [
    path('orders', login_required(OrdersView.as_view(), login_url='users:login'), name='orders'),
    path('pay', login_required(PaymentView.as_view(), login_url='users:login'), name='pay'),
    re_path('^order/(?P<id>[0-9]+)/$', login_required(OrderItemView.as_view(), login_url='users:login'), name='order'),
    re_path('^review/(?P<id>[0-9]+)/$', reviewitem, name='review'),
    re_path('^removeorder/(?P<id>[0-9]+)/$', removeorder, name='removeorder'),
]

users/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from users.views import (
    Login, Register, logout_view,
    Settings, removewatchlist, addwatchlist,
    add_card, delete_card
)
app_name = 'users'
# list of urls for user app
urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('register', Register.as_view(), name='register'),
    path('me', login_required(Settings.as_view(), login_url='users:login'), name='profile'),
    re_path('^addwatchlist/(?P<id>[0-9]+)/$', addwatchlist, name='addwatchlist'),
    re_path('^removewatchlist/(?P<id>[0-9]+)/$', removewatchlist, name='removewatchlist'),
    path('addcard', add_card, name='addcard'),
    path('deletecard', delete_card, name='deletecard'),
    path('logout', logout_view, name='logout')
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.template.defaulttags import register
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import View
from orders.models import (
    Item, Order, Payment, Tables
)
from users.models import (
    User
)
# Create your views here.

# homepage view
class Homepage(View):
    template_name = 'index.html'
    
    def get(self, request, *args, **kwargs):
        main_menu = Item.objects.filter(ordercount__gte=10).all()
        return render(request, self.template_name, {'menu': main_menu})

# menu view
class Menu(View):
    template_name = 'menu.html'
    def get(self, request, *args, **kwargs):
        main_menu = Item.objects.filter(ordercount__gte=10).all()
        return render(request, self.template_name, {'menu': main_menu})


# menu view
class CartView(View):
    template_name = 'cart.html'
    
    def get(self, request, *args, **kwargs):
        user = User.objects.get(username=request.user.username)
        cart = user.cart
        listorders = Order.objects.filter(cart=cart).all()
        cart.totalprice = sum([o.price for o in listorders])
        cart.save()
        return render(request, self.template_name, {'orders': listorders, 'cart': cart})




# Ordertable view
class OrdertableView(View):
    template_name = 'order_table.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
    def post(self, request, *args, **kwargs):
        exclude_keys = ['csrfmiddlewaretoken']
        fields = {key: value for key, value in request.POST.items()}
        saved_fields = {k: fields[k] for k in set(list(fields.keys())) - set(exclude_keys)}
        user = User.objects.get(username=request.user.username)
        table = Tables.objects.filter(date=saved_fields['date'], time=saved_fields['time']).all()
        if not table:
            table = Tables(**saved_fields, reciever=user)
            table.save()
            messages.success(request, "Table has been recervied successfully.")
            return render(request, self.template_name)
        else:
            messages.error(request, "Table already reserved.")
            return render(request, self.template_name)
            

# menu view
class WatchlistView(View):
    template_name = 'watchlist.html'
    
    def get(self, request, *args, **kwargs):
        user = User.objects.get(username=request.user.username)
        favs = user.favourites.all()
        return render(request, self.template_name, {'favs': favs})
    

# item view
class ItemView(View):
    template_name = 'item.html'
    def get(self, request, *args, **kwargs):
        item = Item.objects.get(pk=kwargs['id'])
        similars = Item.objects.filter(category=item.category)
        user = User.objects.get(username=request.user.username)
        cart = user.cart
        orders = Order.objects.filter(cart=cart).all()
        favs = user.favourites.all()
            
        return render(request, self.template_name, {'item': item, 'similars': similars, 'orders':orders, 'favs': favs})


@login_required(login_url="users:login")
def paymentdetails(request, id):
    payment = Payment.objects.get(pk=id)
    return  render(request, 'payment_details.html', {'payment': payment})


@register.filter
def cutprice(price):
    return price - 25
# about view
class About(View):
    template_name = 'about.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

dashboard/templates/includes/addcards.html
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>


<div class="small text-muted mb-3">You have not added a payment card</div>
<button class="btn btn-info" type="button" data-toggle="modal" data-target="#staticBackdrop">Add Payment Card</button>
<!-- Modal -->
<form action="{% url 'users:addcard' %}" method="post">{% csrf_token %}
	<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<div class="text-right"> <i class="fa fa-close close" data-dismiss="modal"></i> </div>
					<div class="tabs mt-3">
					    <ul class="nav nav-tabs" id="myTab" role="tablist">
					        <li class="nav-item" role="presentation"> <a class="nav-link active" id="visa-tab" data-toggle="tab" href="#visa" role="tab" aria-controls="visa" aria-selected="true"> <img src="https://i.imgur.com/sB4jftM.png" style="width: 50px;"> </a> </li>
					    </ul>

					<div class="tab-content" id="myTabContent">
					    <div class="tab-pane fade show active" id="visa" role="tabpanel" aria-labelledby="visa-tab">
					    <div class="mt-4 mx-4">
					        <div class="text-center">
					           <h5>Card Details</h5>
					        </div>
					    <div class="form mt-3">
					        <div class="inputbox mt-4"><span>Cardholder Name</span>  <input type="text" name="owner" class="form-control" required="required"></div>
					        <div class="inputbox mt-2 mb-2"><span>Card Number</span>  <input type="number" name="card-number"  class="form-control" required="required" pattern="^(?:(4[0-9]{12}(?:[0-9]{3})?)|(5[1-5][0-9]{14})|(6(?:011|5[0-9]{2})[0-9]{12})|)$" title="please insert a valid card number"></div>

					        <div class="d-flex flex-row">
					            <div class="inputbox mx-auto"><span>Expiration Date</span><input type="month" name="expired-date" id="expired-date" class="form-control" required="required"></div>
					        <div class="inputbox mx-auto"><span>CVV</span><input type="password" name="cvv" min_length="3" max_length="3" class="form-control" required="required" pattern = "[0-9]+" title="insert valid CVC number"> </div>
					        </div>
							<div class="modal-footer">
								<button type="submit" class="btn btn-success col-sm-3">Add card</button>
								<button type="button" class="btn btn-danger col-sm-3" data-dismiss="modal">Close</button>
							</div>
					 	    </div>
					      </div>
				        </div>
			          </div>
		            </div>
	            </div>
			</div>
		</div>
	</div>
</form>
<hr>
<script type="text/javascript">
// Use Javascript
let today = new Date();
let mm = today.getMonth()+1; //January is 0 so need to add 1 to make it 1!
let yyyy = today.getFullYear();
if(mm<10){
  mm='0'+mm
} 
date = yyyy+'-'+mm;
$('#expired-date').on('click', ()=>{
	$('#expired-date').attr('min', date);
})
</script>

dashboard/templates/includes/cardadded.html
<div class="small text-muted mb-3">This is your card details for this account</div>
    <div class="row">
		<div class="col mb-lg-0 mb-3">
			<div class="card p-2 mx-auto">
				<div class="img-box"> <img src="https://upload.wikimedia.org/wikipedia/commons/a/a4/Mastercard_2019_logo.svg" alt=""> </div>
				<div class="number"> <label style="font-size: 22px;" class="fw-bold" for="">{{request.user.card.cardnumber}}</label> </div>
				<div class="d-flex align-items-center justify-content-between"> <small><span class="fw-bold">Expiry date:</span><span>{{request.user.card.expired_date.month}}/{{request.user.card.expired_date.year}} </span></small> <small><span class="fw-bold">Name:</span><span>{{request.user.card.cardowner}}</span></small> </div>
			</div>
		</div>
    </div>
    <button class="btn btn-primary mt-2 mx-auto col-sm-3" type="button" data-toggle="modal" data-target="#changecard"> Change Card</button>
    <button class="btn btn-danger mt-2 mx-auto col-sm-3" type="button" data-toggle="modal" data-target="#delete-card"> Delete Card</button>
    <hr>

dashboard/templates/includes/change-card.html
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>

<!-- Modal -->
<form action="{% url 'users:addcard' %}" method="post">{% csrf_token %}
	<div class="modal fade" id="changecard" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<div class="text-right"> <i class="fa fa-close close" data-dismiss="modal"></i> </div>
					<div class="tabs mt-3">
					    <ul class="nav nav-tabs" id="myTab" role="tablist">
					        <li class="nav-item" role="presentation"> <a class="nav-link active" id="visa-tab" data-toggle="tab" href="#visa" role="tab" aria-controls="visa" aria-selected="true"> <img src="https://i.imgur.com/sB4jftM.png" style="width: 50px;"> </a> </li>
					    </ul>

					<div class="tab-content" id="myTabContent">
					    <div class="tab-pane fade show active" id="visa" role="tabpanel" aria-labelledby="visa-tab">
					    <div class="mt-4 mx-4">
					        <div class="text-center">
					           <h5>Card Details</h5>
					        </div>
					    <div class="form mt-3">
					        <div class="inputbox mt-4"><span>Cardholder Name</span>  <input type="text" name="owner" class="form-control" required="required"></div>
					        <div class="inputbox mt-2 mb-2"><span>Card Number</span>  <input type="number" name="card-number"  class="form-control" required="required" pattern="^(?:(4[0-9]{12}(?:[0-9]{3})?)|(5[1-5][0-9]{14})|(6(?:011|5[0-9]{2})[0-9]{12})|)$" title="please insert a valid card number"></div>

					        <div class="d-flex flex-row">
					            <div class="inputbox mx-auto"><span>Expiration Date</span><input type="month" name="expired-date" id="expired-dates" class="form-control" required="required"></div>
					        <div class="inputbox mx-auto"><span>CVV</span><input type="password" name="cvv" min_length="3" max_length="3" class="form-control" required="required" pattern = "[0-9]+" title="insert valid CVC number"> </div>
					        </div>
							<div class="modal-footer">
								<button type="submit" class="btn btn-success col-sm-3">Change</button>
								<button type="button" class="btn btn-danger col-sm-3" data-dismiss="modal">Close</button>
							</div>
					 	    </div>
					      </div>
				        </div>
			          </div>
		            </div>
	            </div>
			</div>
		</div>
	</div>
</form>

<script type="text/javascript">
// Use Javascript
let today = new Date();
let mm = today.getMonth()+1; //January is 0 so need to add 1 to make it 1!
let yyyy = today.getFullYear();
if(mm<10){
  mm='0'+mm
} 
date = yyyy+'-'+mm;
$('#expired-dates').on('click', ()=>{
	$('#expired-dates').attr('min', date);
})
</script>

dashboard/templates/includes/clients.html
{% load static %}
  <!-- client section -->

  <section class="client_section layout_padding-bottom">
    <div class="container">
      <div class="heading_container heading_center psudo_white_primary mb_45">
        <h2>
          What Says Our Customers
        </h2>
      </div>
      <div class="carousel-wrap row ">
        <div class="owl-carousel client_owl-carousel">
          <div class="item">
            <div class="box">
              <div class="detail-box">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
                </p>
                <h6>
                  Moana Michell
                </h6>
                <p>
                  magna aliqua
                </p>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="box">
              <div class="detail-box">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
                </p>
                <h6>
                  Mike Hamell
                </h6>
                <p>
                  magna aliqua
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end client section -->

dashboard/templates/includes/delete-card.html

<div class="modal fade" id="delete-card" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-body">
					    <div class="text-right"> <i class="fa fa-close close" data-dismiss="modal"></i> </div>
					  	<div class="tabs mt-3">
              <div class="card">
                <div class="card-body">
                  <form role="form" action="{% url 'users:deletecard' %}" method="post"> {% csrf_token %}
                  <div class="form-group">
                    <p><small class="text-muted"><label class="text-danger">Warning</label> you will delete your current card. sure about that?.Please enter <strong>"your password"</strong> in the fllowing textbox</small><p>
                    <div class="input-group input-group-sm mb-3">
                      <input type="password" id="delete-cards" name="user-password" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
                  </div>

                  </div>
                  <div class="form-group">

                    <button type="submit" id="btndlts" class="btn btn-danger col-sm-12 mb-2">Delete</button>
                    <button type="button" class="btn btn-secondary col-sm-12 mb-2" data-dismiss="modal">cancle</button>
                  </div>
                </form>
                </div>
              </div>
				</div>
			</div>
		</div>
    
    

dashboard/templates/includes/menu.html
{% load static %}

<style>
.dropdown.dropdown-lg .dropdown-menu {
    margin-top: -1px;
    padding: 6px 20px;
}
.input-group-btn .btn-group {
    display: flex !important;
}
.btn-group .btn {
    border-radius: 0;
    margin-left: -1px;
}
.btn-group .btn:last-child {
    border-top-right-radius: 4px;
    border-bottom-right-radius: 4px;
}
.btn-group .form-horizontal .btn[type="submit"] {
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
}
.form-horizontal .form-group {
    margin-left: 0;
    margin-right: 0;
}
.form-group .form-control:last-child {
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
}

@media screen and (min-width: 768px) {
    #adv-search {
        width: 500px;
        margin: 0 auto;
    }
    .dropdown.dropdown-lg {
        position: static !important;
    }
    .dropdown.dropdown-lg .dropdown-menu {
        min-width: 500px;
    }
}
</style>
  <!-- food section -->
  <section class="food_section layout_padding-bottom">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Our Main Menu
        </h2>
      </div>

      <ul class="filters_menu">
        <li class="active" data-filter="*">All</li>
        <li data-filter=".burger">Burger</li>
        <li data-filter=".pizza">Pizza</li>
        <li data-filter=".pasta">Pasta</li>
        <li data-filter=".fries">Fries</li>
        <li data-filter=".drinks">Drinks</li>
        <li data-filter=".salads">Salads</li>
        <li data-filter=".dessert">Dessert</li>
      </ul>

      <div class="filters-content">
        <div class="row grid">
          {% for item in menu %}
          <div class="col-sm-6  col-lg-4 all {{item.category}}">
            <a class="text-white" href="{% url 'dashboard:item' item.id %}"> 
            <div {% if item.status == 'out of stock' %}style="pointer-events:none; opacity: 0.4;"{% endif %} class="box">
              <div>
                
                <div class="img-box">
                  <img style="width:100%;object-fit: scale-down;"  src="{{item.img}}" alt="">
                </div>
                <div class="detail-box">
                  
                    <h5>
                      {{item.title}}
                    </h5>
                  </a>
                  <div class="options">
                    <h6>
                      ${{item.price}}
                    </h6>
                  
                    <a href="" data-toggle="modal" data-target="#product_view{{item.id}}">
                      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                        <g>
                          <g>
                            <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                         c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                         C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                         c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                         C457.728,97.71,450.56,86.958,439.296,84.91z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                         c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                          </g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% include 'includes/orderitem.html' with item=item%}
          {% endfor %}
        </div>
      </div>
      <div class="btn-box">
        <a href="{% url 'orders:orders' %}">
          View More
        </a>
      </div>
    </div>
  </section>

  <!-- end food section -->

dashboard/templates/includes/orderitem.html

<style>
    .product_view .modal-dialog{max-width: 800px; width: 100%;}
    .pre-cost{text-decoration: line-through; color: #a5a5a5;}
    .space-ten{padding: 20px 0;}
</style>
<div class="text-dark modal fade product_view" id="product_view{{item.id}}">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4 mx-auto product_img">
                        <img style="object-fit: contain;" src="{{item.img}}" class="h-100 w-100">
                    </div>
                    <div class="col-md-8 product_content">
                        <h3 class="modal-title">{{item.title}}</h3>

                        <div class="rating">
                             {% for i in item.rating.all|ratesavg|inrange %}<span class="text-warning fa fa-star"></span>{% endfor %}{% for i in item.rating.all|ratesavg|diffrange %}<span class="text-dark fa fa-star"></span>{% endfor %}
                            ({{item.rating.all|length}} reviews)
                        </div>
                        <p>{{item.description}}</p>
                        <h3 class="cost"><span class="glyphicon glyphicon-usd"></span>Price: {{item.price}}$</h3>
                        <div class="row">
                         <form class="row form-group" action="{% url 'orders:order' item.id %}" method="post"> {% csrf_token %}
                            <div class="col-md-4 col-sm-6 col-xs-12">
                                <select class="form-control" name="size" required>
                                    <option selected disabled>size</option>
                                    {% if item.category in 'pasta, burger, pizza, salads' %}
                                        <option value="large">Large</option>
                                        <option value="medium">Medium</option>
                                        <option value="small">Small</option>
                                    {% elif item.category == 'drinks' %}
                                        <option value="330ml">330ml</option>
                                        <option value="1 Litre">1 Litre</option>
                                        <option value="2 Litres">2 Litres</option>
                                        <option value="2.5 Litres">2.5 Litres</option>
                                    {% elif item.category == 'dessert' %}
                                        <option value="250g">250g</option>
                                        <option value="500g">500g</option>
                                        <option value="1 Kg">1 Kg</option>
                                        <option value="2 Kg">2 Kg</option>
                                        <option value="2.5 Kg">2.5 Kg</option>
                                        <option value="5 Kg">5 Kg</option>
                                        <option value="10 Kg">10 Kg</option>
                                    {% endif %}
                                </select>
                            </div>
                            <!-- end col -->
                            <div class="col-md-4 col-sm-6 col-xs-12">
                                <select class="form-control" name="type" required>
                                    <option selected disabled>Type</option>
                                    {% if item.category in 'pizza, burger, pasta, salads' %}
                                        <option value="mild">Mild</option>
                                        <option value="spicy">Spicy</option>
                                    {% elif item.category == 'drinks' %}
                                        <option value="diet">Diet</option>
                                        <option value="no-diet">No Diet</option>
                                    {% elif item.category == 'dessert' %}
                                        <option value="classic">classic</option>
                                        <option value="chocolatty">chocolatty</option>
                                        <option value="nutty">nutty</option>
                                        <option value="chocolatty-nutty">chocolatty-nutty</option>
                                    {% endif %}
                                </select>
                            </div>
                            <!-- end col -->
                            <div class="col-md-4 col-sm-12">
                                <input type="number" class="form-control" name="quantity" value="1" id="qty" min="1" placeholder="QTY">
                            </div>
                            <!-- end col -->
                        </div>
                        <div class="space-ten"></div>
                        <div class="mr-auto float-right">
                             <button type="submit" class="btn btn-primary"><i class="fa fa-cart-plus"></i> Add to Cart</button>
                            {% if item in request.user.favourites.all %}
                                <a href="{% url 'users:removewatchlist' item.id %}"> <button type="button" class="btn btn-danger"><i class="fa fa-heart"></i> Remove from Wishlist</button></a>
                            {% else %}
                                <a href="{% url 'users:addwatchlist' item.id %}"> <button type="button" class="btn btn-primary"><i class="fa fa-heart"></i> Add to Wishlist</button></a>
                            {% endif %}
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

dashboard/templates/includes/rate.html
<style>
 .mb-10 {
     margin-bottom: 10px
 }

 .mt-100 {
     margin-top: 100px
 }

 .modal-content {
     border-radius: 1px
 }

 .modal-header {
     border-bottom: 1px solid #ffffff
 }

 .btn:focus {
     box-shadow: 0 0 0 0.2rem rgb(255, 255, 255)
 }

 .close:focus {
     box-shadow: 0 0 0 0.2rem rgb(255, 255, 255)
 }

 .btn.btn-out {
     outline: 1px solid #fff;
     outline-offset: -5px
 }

 .btn {
     border-radius: 2px;
     text-transform: capitalize;
     font-size: 15px;
     padding: 10px 19px;
     cursor: pointer;
     color: #fff
 }

 .form-control:focus {
     box-shadow: 0 0 0 0.2rem rgb(255, 255, 255)
 }

 .form-control {
     border-radius: 0px !important
 }
 
.starrating > input {display: none;}  /* Remove radio buttons */

.starrating > label:before { 
  content: "\f005"; /* Star */
  margin: 2px;
  font-size: 4em;
  font-family: FontAwesome;
  display: inline-block; 
}

.starrating > label
{
  color: #222222; /* Start color when not clicked */
}

.starrating > input:checked ~ label
{ color: #ffca08 ; } /* Set yellow color when star checked */

.starrating > input:hover ~ label
{ color: #ffca08 ;  } /* Set yellow color when star hover */
</style>
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>{{item.title}}</h4> 
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form action="{% url 'orders:review' item.id %}" method="post"> {% csrf_token %}
                <div class="modal-body">
                    <div class="starrating risingstar d-flex justify-content-center flex-row-reverse">
                        <input type="radio" id="star5" name="rate" value="5" /><label for="star5" title="5 star">5</label>
                        <input type="radio" id="star4" name="rate" value="4" /><label for="star4" title="4 star">4</label>
                        <input type="radio" id="star3" name="rate" value="3" /><label for="star3" title="3 star">3</label>
                        <input type="radio" id="star2" name="rate" value="2" /><label for="star2" title="2 star">2</label>
                        <input type="radio" id="star1" name="rate" value="1" /><label for="star1" title="1 star">1</label>
                    </div>  
                    <textarea style="resize: none; height: 200px;" type="text" name="description" class="form-control mb-10" placeholder="What would you like to say about this product"></textarea>
                    
                </div>
                <div class="modal-footer">
                    <button class="btn btn-out btn-primary btn-square">send review</button>
                </div>
            </form>

        </div>
    </div>
    <script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'></script>
    <script type='text/javascript' src=''></script>
    <script type='text/javascript' src=''></script>
</div>
