Foodex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('orders.urls')),
    path('', include('users.urls')),
]

dashboard/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from dashboard.views import (
    Homepage, ItemView,
    Menu, About, CartView, WatchlistView, OrdertableView, paymentdetails
)

app_name = 'dashboard'
# list of urls for dashborad
urlpatterns = [
    path('', Homepage.as_view(), name='home'),
    path('menu', Menu.as_view(), name='menu'),
    path('about', About.as_view(), name='about'),
    path('cart', login_required(CartView.as_view(), login_url='users:login'), name='cart'),
    path('watchlist', login_required(WatchlistView.as_view(), login_url='users:login'), name='watchlist'),
    path('ordertable', login_required(OrdertableView.as_view(), login_url='users:login'), name='ordertable'),
    re_path('^item/(?P<id>[0-9]+)/$', login_required(ItemView.as_view(), login_url='users:login'), name='item'),
    re_path('^paymentdetails/(?P<id>[0-9]+)/$', paymentdetails, name='paymentdetails'),
]

users/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from users.views import (
    Login, Register, logout_view,
    Settings, removewatchlist, addwatchlist,
    add_card, delete_card
)
app_name = 'users'
# list of urls for user app
urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('register', Register.as_view(), name='register'),
    path('me', login_required(Settings.as_view(), login_url='users:login'), name='profile'),
    re_path('^addwatchlist/(?P<id>[0-9]+)/$', addwatchlist, name='addwatchlist'),
    re_path('^removewatchlist/(?P<id>[0-9]+)/$', removewatchlist, name='removewatchlist'),
    path('addcard', add_card, name='addcard'),
    path('deletecard', delete_card, name='deletecard'),
    path('logout', logout_view, name='logout')
]

users/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from orders.models import (
    Item
)
# Create your models here.


# create User model
class User(AbstractUser):
    # relations
    favourites    = models.ManyToManyField('orders.Item', related_name='favourite', null=True, blank=True)
    cart          = models.OneToOneField('users.Cart', on_delete=models.CASCADE, related_name='usercart', null=True, blank=True, db_constraint=False)
    card          = models.OneToOneField('users.Card', on_delete=models.DO_NOTHING, related_name='card', null=True, blank=True, db_constraint=False)
    # premative fields
    location      =  models.CharField(max_length=250, null=False, blank=False)
    phone         =  models.CharField(max_length=11, null=False, blank=False, unique=True)


    class Meta:
        verbose_name = "user"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.username


class Card(models.Model):
    cardowner             = models.CharField(max_length=25, null=False, blank=False, default='admin')
    cardnumber            = models.IntegerField(unique=True, null=False, blank=False)
    cvv                   = models.IntegerField(null=False, blank=False, validators=[MaxValueValidator(999), MinValueValidator(100)])
    expired_date          = models.DateField()
    budget                = models.DecimalField(default=320.50, max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = "card"
        verbose_name_plural = "Cards"

    def __str__(self):
        return f'{self.cardnumber}'


class Cart(models.Model):

    state_choices = [
        (0, 'Deactived'),
        (1, 'actived')
    ]

    # relations
    # premative fields
    state       = models.BooleanField(default=0, choices=state_choices)
    totalprice  = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    class Meta:
        verbose_name = "cart"
        verbose_name_plural = "Carts"

    def __str__(self):
        return f"Cart id: {self.id} Cart now is: {self.state}"


class Rating(models.Model):
    # relations
    user         = models.ForeignKey('users.User', related_name='comment', null=True, blank=True, on_delete=models.CASCADE, unique=False)
    item         = models.ForeignKey('orders.Item', on_delete=models.CASCADE, related_name='rating', null=True, blank=True, unique=False)
    # premitive attrs
    rate         = models.IntegerField()
    description  = models.TextField(null=False, blank=False)
    created_at   = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "rate"
        verbose_name_plural = "Rates"

    def __str__(self):
        return f"{self.user.username} has rated {self.item.title} with {self.rate} starts"




users/views.py
import random as rd
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import View
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from threading import Timer
from django.contrib import messages
from users.models import (
    User, Cart, Card
)
from orders.models import (
    Item, Payment
)
# from users.models import User
# Create your views here.


# Login view
class Login(View):
    template_name = './users/login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        username = request.POST["username"]
        password = request.POST["password"]
        
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect("dashboard:home")
        else:
            messages.error(request, "Invalid username and/or password.")
            return render(request, self.template_name)


# Register view
class Register(View):
    template_name = './users/register.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        exclude_keys = ['confirm_password', 'csrfmiddlewaretoken']
        fields = {key: value for key, value in request.POST.items()}
        saved_fields = {k: fields[k] for k in set(list(fields.keys())) - set(exclude_keys)}
        
        # dynamic check empty fields
        for k, v in fields.items():
            if len(v) <= 0:
                messages.error(request, f"{k} field is empty.")
                return render(request, self.template_name)
        if fields['password'] != fields['confirm_password']:
            messages.error(request, "passwords must be identical.")
            return render(request, self.template_name)
        # Attempt to create new user
        try:
            
            cart = Cart()
            cart.save()
            user = User.objects.create_user(**saved_fields, cart=cart)
            user.save()
            return redirect("users:login")
        except IntegrityError:
            messages.error(request, "Username already taken.")
            return render(request, self.template_name)
        

# Register view
class Settings(View):
    template_name = './users/profile_settings.html'
    
    def dispatch(self, request, *args, **kwargs):
        timerpay = Timer(10, change_payment_status, args=[request])
        timerpay.start()
        return super(Settings, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        user = User.objects.get(username=request.user.username)
        payments = Payment.objects.filter(payer=user).all()
        return render(request, self.template_name, {'payments': payments})

    
@login_required(login_url="users:login")
def addwatchlist(request, id):
    item = Item.objects.filter(pk=id)

    user = User.objects.get(username=request.user.username)
    favourites = user.favourites.all()
    if item[0] not in favourites:
        user.favourites.set(favourites.union(item))
        user.save()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url="users:login")
def removewatchlist(request, id):
    item = Item.objects.filter(pk=id)
    user = User.objects.get(username=request.user.username)
    favourites = user.favourites.all()
    if item[0] in favourites:
        user.favourites.set(user.favourites.difference(item))
        user.save()
    return redirect(request.META.get('HTTP_REFERER'))



@login_required(login_url="users:login")
@require_http_methods("POST")
def add_card(request):
    inputs = { key: value
            for key, value in request.POST.items()
            if key in ['owner', 'card-number', 'expired-date', 'cvv']}
    inputs['expired-date'] = inputs['expired-date'] + '-1'
    
    try:
        card = Card.objects.get(cardnumber=inputs['card-number'])
        messages.error(request, "This card already exists for another user.")
        return redirect(reverse('users:profile') + '#bill')
    except:
        user = User.objects.get(username=request.user.username)
        try:
            user.card.delete()
            card = Card(cardowner=inputs['owner'], cardnumber=inputs['card-number'],
                         expired_date=inputs['expired-date'], cvv=inputs['cvv'], budget=rd.uniform(300.80, 2400.90))
            card.save()
            user.card = card
            user.save()
        except:
            card = Card(cardowner=inputs['owner'], cardnumber=inputs['card-number'],
                         expired_date=inputs['expired-date'], cvv=inputs['cvv'], budget=rd.uniform(300.80, 2400.90))
            card.save()
            user.card = card
            user.save()
        messages.success(request, "Card added successfully")
        return redirect(reverse("users:profile")+"#bill")


@login_required(login_url="users:login")
@require_http_methods("POST")
def delete_card(request):
    exclude_keys = ['csrfmiddlewaretoken']
    fields = {key: value for key, value in request.POST.items()}
    saved_fields = {k: fields[k] for k in set(list(fields.keys())) - set(exclude_keys)}
    user = User.objects.get(username=request.user.username)
    auth = authenticate(request, username=user.username, password=saved_fields['user-password'])
    if auth:
        try:
            user.card.delete()
            messages.success(request, "Card deleted successfully")
            return redirect(reverse("users:profile")+"#bill")
        except:
            messages.error(request, "No added Cards to delete")
            return redirect(reverse("users:profile")+"#bill")
    messages.error(request, "wrong password please try again!!")
    return redirect(request.META.get('HTTP_REFERER'))

# logout
@login_required(login_url="users:login")
def logout_view(request):
    logout(request)
    return redirect("users:logout")



def change_payment_status(request):
    user = User.objects.get(username=request.user.username)
    payments = Payment.objects.filter(payer=user).all()
    
    for payment in payments:
        payment.status = 'Delivered'
        payment.paid = 'paid'
        payment.save()
    

users/templates/users/layout.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static './icons/favicon.png' %}" type="">

  <title> foodex: {% block title %}{% endblock %}</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static './users/css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static './users/css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static './users/css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static './users/css/responsive.css' %}" rel="stylesheet" />

</head>
<body>
    <div class="hero_area">
        <div class="bg-box">
          <img src="{% static './users/img/hero-bg.jpg' %}" alt="">
        </div>
        <!-- header section strats -->
        <header class="header_section">
          <div class="container">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
              <a class="navbar-brand" href="{% url 'dashboard:home' %}">
                <span>
                  foodex
                </span>
              </a>
    
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class=""> </span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav px-0  mr-auto ">

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:menu' %}">Main Menu</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:about' %}">About</a>
                  </li>
                </ul>
                <div class="user_option"> 
                <div class="user_option">
                  <a href="{% url 'users:login' %}" class="user_link">
                    <i class="fa fa-user" aria-hidden="true"></i>
                  </a>
                  <a href="" class="order_online">
                    Order Online
                  </a>
                </div>
              </div>
            </nav>
          </div>
        </header>
        <!-- end header section -->
    <main> {% block main %}{% endblock  %} </main>
</body>


  <!-- jQery -->
  <script src="{% static './users/js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static './users/js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static './users/js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->
  </html>

users/templates/users/login.html
{% extends './layout.html' %}
{% load static %}
{% block  title %}Login{% endblock  %}
{% block main %}
<section class="vh-100">
    <div class="container-fluid">
      <div class="row-8">
        <div class="col-sm-6 text-black">
  
          <div class="px-5 ms-xl-4">
            <i class="fa fa-crow fa-2x me-3 pt-5 mt-xl-4"></i>
            <span class="h1 fw-bold mb-0 "></span>
          </div>
  
          <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
  
            <form action="{% url 'users:login' %}" method="POST" style="width: 23rem;"> {% csrf_token %}
              <h3 class="fw-normal mb-3 pb-3 text-white" style="letter-spacing: 1px;">Log in</h3>
              {% include 'includes/message.html' %}
              <div class="form-outline mb-2">
                <label class="form-label text-white" for="username">Username</label>
                <input type="text" id="username" name="username" class="form-control form-control" placeholder='type your username' required/>
              </div>
  
              <div class="form-outline mb-4">
                <label class="form-label text-white" for="password">Password</label>
                <input type="password" id="password" name="password" class="form-control form-control" placeholder='type your password' required/>
              </div>

              <div class="row pt-0 mb-4">
                <div class="col-sm-12 d-flex justify-content-center text-center">
                    <button class="btn btn-warning btn-block" type="submit">Login</button>
                </div>
              </div>

              <div class="row pt-0 mb-2">
                <div class="col-sm-12 d-flex justify-content-center text-center">
                    <a id="ask-for-password" class=" text-primary col-sm-6 mx-sm-auto" href="#">Forgot password?</a>
                    <a id="ask-for-register" class=" text-primary col-sm-6 mx-sm-auto" href="{% url 'users:register' %}">Haven't Registered?</a>
                </div>
              </div>
            </form>
  
          </div>
  
        </div>  
</section>
{% endblock  %}

users/templates/users/register.html
{% extends './layout.html' %}
{% load static %}
{% block title %}Register{% endblock  %}
{% block main %}
<!-- start section -->
<section class="vh-100">
    <div class="container-fluid">
      <div class="row-8">
        <!-- start block-->
        <div class="col-sm-6 text-black">
          <div class="px-5 ms-xl-4">
            <i class="fa fa-crow fa-2x me-3 pt-5 mt-xl-4"></i>
            <span class="h1 fw-bold mb-0 "></span>
          </div>

          <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
            
            <!--start form-->
            <form action="{% url 'users:register' %}" method="POST" style="width: 23rem;"> 
              {% csrf_token %}
              <h3 class="fw-normal mb-3 pb-3 text-white" style="letter-spacing: 1px;">Sign Up</h3>
              {% include 'includes/message.html' %}
              <!-- start names-->
              <div class="row mb-2">
                <div class="col-sm-6 form-outline">
                  <label class="form-label text-white" for="first_name">First Name</label>
                  <input type="text" id="first_name" name="first_name" class="form-control form-control" placeholder='first name' required/>
                </div>
                <div class="col-sm-6 form-outline">
                  <label class="form-label text-white" for="last_name">Last Name</label>
                  <input type="text" id="last_name" name="last_name" class="form-control form-control" placeholder='last name' required/>
                </div>
              </div>
              <!-- end name-->

              <!-- start username -->
              <div class="form-outline mb-2">
                <label class="form-label text-white" for="username">username</label>
                <input type="text" id="username" name="username" class="form-control form-control" placeholder=' username' required/>
              </div>
              <!-- end username -->

              <!-- start passwords -->
              <div class="row mb-2">
                <div class="col-sm-6 form-outline">
                  <label class="form-label text-white" for="password">Password</label>
                  <input type="password" id="password" name="password" class="form-control form-control" placeholder='password' required/>
                </div>
                <div class="col-sm-6 form-outline">
                  <label class="form-label text-white" for="confitm-password">Confirm Password</label>
                  <input type="password" id="confitm-password" name="confirm_password" class="form-control form-control" placeholder='confirm password' required/>
                </div>
            </div>
            <!-- end passwords-->
            
            <!-- start other -->
            <div class="row mb-4">
              <!-- start phone-->
              <div class="col-sm-6 form-outline">
                <label class="form-label text-white" for="phone">phone</label>
                <input type="tel" id="phone" name="phone" class="form-control form-control" placeholder='phone number' pattern="^01[0-2,5]{1}[0-9]{8}$" required/>
              </div>
              <!-- end phone-->

              <!-- start location -->
              <div class="col-sm-6 form-outline">
                <label class="form-label text-white" for="location">location</label>
                <input type="text" id="location" name="location" class="form-control form-control" placeholder='address' required/>
              </div>
              <!-- end location -->
            </div>
            <!-- end others -->

              <!-- submit-->
              <div class="pt-0 mb-2">
                <button class="btn btn-warning btn-block" type="submit">Sign Up</button>
              </div>
              <!-- end passwords -->

              <!-- start options -->
              <div class="row">
                <div class="col-sm-12 d-flex justify-content-center text-center">
                  <a id="ask-for-login" class="text-primary" href="{% url 'users:login' %}">i Have an account</a> 
                </div>
              </div>
              <!-- end options -->          
            </form>
            <!-- End from -->
          </div>
        </div>  
</section>
<!-- end section -->
<script>
  var loc = document.querySelector('#location');

  function getReverseGeocodingData(pos) {
    var latlng = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude);
    // This is making the Geocode request
    var geocoder = new google.maps.Geocoder();
    geocoder.geocode({ 'latLng': latlng },  (results, status) =>{
        if (status !== google.maps.GeocoderStatus.OK) {
            alert(status);
        }
        // This is checking to see if the Geoeode Status is OK before proceeding
        if (status == google.maps.GeocoderStatus.OK) {
            var address = (results[0].formatted_address);
            loc.value = address;
        }
    });
  }
  function displayError () {
    alert('Sorry location not found :(');
  }
  loc.addEventListener('click', () => {
    var options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumAge: 0
    };
    /*empty string*/
    if (loc.value.length > 0){
        loc.value = '';
    }
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(getReverseGeocodingData, displayError, options);
    } else { 
      alert("Geolocation is not supported by this browser.");
    }
  });
</script> 
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBPQ7PC_2JN_9jNw4z3N-PIsOtJF6HY-Hs&libraries=places&callback=initMap" async defer></script>

{% endblock  %}