Foodex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('orders.urls')),
    path('', include('users.urls')),
]

dashboard/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from dashboard.views import (
    Homepage, ItemView,
    Menu, About, CartView, WatchlistView, OrdertableView, paymentdetails
)

app_name = 'dashboard'
# list of urls for dashborad
urlpatterns = [
    path('', Homepage.as_view(), name='home'),
    path('menu', Menu.as_view(), name='menu'),
    path('about', About.as_view(), name='about'),
    path('cart', login_required(CartView.as_view(), login_url='users:login'), name='cart'),
    path('watchlist', login_required(WatchlistView.as_view(), login_url='users:login'), name='watchlist'),
    path('ordertable', login_required(OrdertableView.as_view(), login_url='users:login'), name='ordertable'),
    re_path('^item/(?P<id>[0-9]+)/$', login_required(ItemView.as_view(), login_url='users:login'), name='item'),
    re_path('^paymentdetails/(?P<id>[0-9]+)/$', paymentdetails, name='paymentdetails'),
]

orders/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from orders.views import (
    OrdersView, OrderItemView, PaymentView,
    removeorder, reviewitem
)
app_name = 'orders'
# list of urls for dashborad
urlpatterns = [
    path('orders', login_required(OrdersView.as_view(), login_url='users:login'), name='orders'),
    path('pay', login_required(PaymentView.as_view(), login_url='users:login'), name='pay'),
    re_path('^order/(?P<id>[0-9]+)/$', login_required(OrderItemView.as_view(), login_url='users:login'), name='order'),
    re_path('^review/(?P<id>[0-9]+)/$', reviewitem, name='review'),
    re_path('^removeorder/(?P<id>[0-9]+)/$', removeorder, name='removeorder'),
]

users/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from users.views import (
    Login, Register, logout_view,
    Settings, removewatchlist, addwatchlist,
    add_card, delete_card
)
app_name = 'users'
# list of urls for user app
urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('register', Register.as_view(), name='register'),
    path('me', login_required(Settings.as_view(), login_url='users:login'), name='profile'),
    re_path('^addwatchlist/(?P<id>[0-9]+)/$', addwatchlist, name='addwatchlist'),
    re_path('^removewatchlist/(?P<id>[0-9]+)/$', removewatchlist, name='removewatchlist'),
    path('addcard', add_card, name='addcard'),
    path('deletecard', delete_card, name='deletecard'),
    path('logout', logout_view, name='logout')
]

dashboard/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class Item(models.Model):


    # global variables
    type_options = [
        ('new', 'new'),
        ('sale', 'sale'),
        ('defualt', 'defualt'),
        ('out of stock', 'out of stock')
    ]
    cat_options = [
        ('pizza', 'pizza'),
        ('pasta', 'pasta'),
        ('burger', 'burger'),
        ('drinks', 'drinks'),
        ('salads', 'salads'),
        ('dessert', 'dessert')]
    # relations attr

    # premitive attrs
    img           = models.URLField(max_length=1024, unique=True, null=True, blank=True)
    title         = models.CharField(max_length=64, null=False, blank=False, unique=True)
    price         = models.DecimalField(max_digits=5, decimal_places=2, null=False, blank=False)
    description   = models.TextField(null=False, blank=False)
    category      = models.CharField(max_length=10, null=False, blank=False, choices=cat_options)
    quantity      = models.IntegerField(validators=[MinValueValidator(1)], default=50)
    status        = models.CharField(max_length=25, null=False, blank=False, choices=type_options, default='defualt')
    ordercount    = models.IntegerField(default=0)
    
    class Meta:
        verbose_name = "item"
        verbose_name_plural = "Items"

    def __str__(self):
        return self.title


class Order(models.Model):

    # relations attr
    item             = models.ForeignKey('orders.Item', on_delete=models.CASCADE, related_name='ordereditem')
    cart             = models.ForeignKey('users.Cart', on_delete=models.CASCADE, related_name='cart', null=True, blank=True, db_constraint=False)
    # premitive attrs
    orderid          = models.CharField(max_length=7, null=False, blank=False, unique=True, default='#123456')
    created_on       = models.DateTimeField(auto_now_add=True)
    quantity         = models.IntegerField(validators=[MinValueValidator(1)])
    price            = models.DecimalField(max_digits=5, decimal_places=2, null=False, blank=False)
    size             = models.CharField(max_length=10, null=False, blank=False)
    type             = models.CharField(max_length=10, null=False, blank=False)
 
    class Meta:
        verbose_name = "order"
        verbose_name_plural = "Orders"
          
    def __str__(self):
        return f'Order {self.orderid}: {self.created_on.strftime("%b %d %Y %I:%M %p")}'



    
class Payment(models.Model):
    method_choices = [
        ('Mastercard', 'Mastercard'),
        ('Visa', 'Visa'),
        ('Bank Account', 'Bank Account'),
        ('Paypal', 'Paypal')
    ]
    paid_choices = [
        ('upon receipt', 'upon receipt'),
        ('paid', 'paid')
    ]
    status_choices = [
        ('Delevering', 'Delevering'),
        ('Delivered', 'Delivered')
    ]
    # relations
    payer                 = models.ForeignKey('users.User', related_name='user', on_delete=models.CASCADE, null=True, blank=True)
    orders                = models.ManyToManyField('orders.Order', related_name='orders')
    # premetive attrs
    code                  = models.CharField(max_length=9, null=False, blank=False, default=f'#18776527')
    date                  = models.DateTimeField(auto_now_add=True)
    method                = models.CharField(max_length=15, null=False, blank=False, default='Mastercard', choices=method_choices)
    paid                  = models.CharField(max_length=15, default='upon receipt', choices=paid_choices)
    status                = models.CharField(max_length=15, default='Delevering', choices=status_choices)
    price                 = models.DecimalField(max_digits=10, decimal_places=2, default=0) 

    class Meta:
        verbose_name = "payment"
        verbose_name_plural = "Payments"

    def __str__(self):
        return f'{self.code}'



class Tables(models.Model):

    # relations
    reciever              = models.ForeignKey('users.User', related_name='reciever', on_delete=models.CASCADE, null=True, blank=True)
    # premetive attrs
    name                  = models.CharField(max_length=100, null=False, blank=False)              
    email                 = models.CharField(max_length=50, null=True, blank=True)
    phone                 =  models.CharField(max_length=11, null=False, blank=False)
    count                 = models.IntegerField()
    date                  = models.DateField(auto_now_add=True)
    time                  = models.TimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = "table"
        verbose_name_plural = "Tables"

    def __str__(self):
        return f'Table recieved from {self.name}'

dashboard/views.py
from django.template.defaulttags import register
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import View
from orders.models import (
    Item, Order, Payment, Tables
)
from users.models import (
    User
)
# Create your views here.

# homepage view
class Homepage(View):
    template_name = 'index.html'
    
    def get(self, request, *args, **kwargs):
        main_menu = Item.objects.filter(ordercount__gte=10).all()
        return render(request, self.template_name, {'menu': main_menu})

# menu view
class Menu(View):
    template_name = 'menu.html'
    def get(self, request, *args, **kwargs):
        main_menu = Item.objects.filter(ordercount__gte=10).all()
        return render(request, self.template_name, {'menu': main_menu})


# menu view
class CartView(View):
    template_name = 'cart.html'
    
    def get(self, request, *args, **kwargs):
        user = User.objects.get(username=request.user.username)
        cart = user.cart
        listorders = Order.objects.filter(cart=cart).all()
        cart.totalprice = sum([o.price for o in listorders])
        cart.save()
        return render(request, self.template_name, {'orders': listorders, 'cart': cart})




# Ordertable view
class OrdertableView(View):
    template_name = 'order_table.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
    def post(self, request, *args, **kwargs):
        exclude_keys = ['csrfmiddlewaretoken']
        fields = {key: value for key, value in request.POST.items()}
        saved_fields = {k: fields[k] for k in set(list(fields.keys())) - set(exclude_keys)}
        user = User.objects.get(username=request.user.username)
        table = Tables.objects.filter(date=saved_fields['date'], time=saved_fields['time']).all()
        if not table:
            table = Tables(**saved_fields, reciever=user)
            table.save()
            messages.success(request, "Table has been recervied successfully.")
            return render(request, self.template_name)
        else:
            messages.error(request, "Table already reserved.")
            return render(request, self.template_name)
            

# menu view
class WatchlistView(View):
    template_name = 'watchlist.html'
    
    def get(self, request, *args, **kwargs):
        user = User.objects.get(username=request.user.username)
        favs = user.favourites.all()
        return render(request, self.template_name, {'favs': favs})
    

# item view
class ItemView(View):
    template_name = 'item.html'
    def get(self, request, *args, **kwargs):
        item = Item.objects.get(pk=kwargs['id'])
        similars = Item.objects.filter(category=item.category)
        user = User.objects.get(username=request.user.username)
        cart = user.cart
        orders = Order.objects.filter(cart=cart).all()
        favs = user.favourites.all()
            
        return render(request, self.template_name, {'item': item, 'similars': similars, 'orders':orders, 'favs': favs})


@login_required(login_url="users:login")
def paymentdetails(request, id):
    payment = Payment.objects.get(pk=id)
    return  render(request, 'payment_details.html', {'payment': payment})


@register.filter
def cutprice(price):
    return price - 25
# about view
class About(View):
    template_name = 'about.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

orders/views.py
import random as rd
from django.template.defaulttags import register
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import View
from threading import Timer
# custom modules
from orders.models import (
    Payment
)
from orders.models import (
    Item, Order
)
from users.models import (
    User, Rating
)


# Create your views here.

# All Orders view
class OrdersView(View):
    template_name = './orders/index.html'
    
    def dispatch(self, request, *args, **kwargs):
        timer = Timer(60, change_status)
        timer.start()
        return super(OrdersView, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        items = Item.objects.all()
        user = User.objects.get(username=request.user.username)
        favs = user.favourites.all()
        cart = user.cart
        orders = Order.objects.filter(cart=cart).all()
        for i in items:
            if i.quantity == 0:
                i.status = 'out of stock'
        
        return render(request, self.template_name, {'items': items, 'orders': orders, 'favs': favs})
            


# Payment view
class PaymentView(View):
    # template_name = './orders/index.html'
        
    def post(self, request, *args, **kwargs):
        user = User.objects.get(username=request.user.username)
        paid = request.POST.get('paid', 'paid')
        cart = user.cart
        card = user.card
        orders = Order.objects.filter(cart=cart).all()
        
        if paid == 'paid' and cart.totalprice < card.budget:
            payment = Payment.objects.create(code=f"#{rd.randint(10000000, 99999999)}", payer=user)
            payment.orders.set(orders)
            payment.paid = paid
            cart.totalprice += 25
            payment.price = cart.totalprice
            payment.save()
            card.budget -= cart.totalprice
            card.save()
                
            # set objects to default
            cart.totalprice = 0
            if cart.state:
                cart.state = False
            cart.save()
            for order in orders:
                order.cart = None
                order.save()
            messages.success(request, "Payment has been successfully.")
            return redirect(reverse('dashboard:cart')) #redirect(reverse('users:profile') + '#bill')
        elif paid == 'upon receipt':
            payment = Payment.objects.create(code=f"#{rd.randint(10000000, 99999999)}", payer=user)
            payment.orders.set(orders)
            payment.paid = paid
            cart.totalprice += 25
            payment.price = cart.totalprice
            payment.save()

            # set objects to default
            cart.totalprice = 0
            if cart.state:
                cart.state = False
            cart.save()
            for order in orders:
                order.cart = None
                order.save()
            messages.success(request, "Payment has been successfully.")
            return redirect(reverse('dashboard:cart')) #redirect(reverse('users:profile') + '#bill')
        else:
            messages.error(request, "You don't have enough money.")
            return redirect(request.META.get('HTTP_REFERER'))
            


# All Orders view
class OrderItemView(View):
        
    def post(self, request, *args, **kwargs):
        exclude_keys = ['csrfmiddlewaretoken']
        fields = {key: value for key, value in request.POST.items()}
        saved_fields = {k: fields[k] for k in set(list(fields.keys())) - set(exclude_keys)}
        
        orderid = f'#{rd.randint(100000, 999999)}'
        item = Item.objects.get(pk=kwargs['id'])
        currentuser = User.objects.get(username=request.user.username)
        currentcart = currentuser.cart
        if not currentcart.state:
            currentcart.state = True
            currentcart.save()
        
        keys = {k: fields[k] for k in set(list(saved_fields.keys())) - set(['quantity'])}
        orders = Order.objects.filter(item=item, cart=currentcart, **keys).all()
        if len(orders) == 1:
            orders[0].quantity += int(saved_fields['quantity'])
            orders[0].price = int(orders[0].quantity) * float(item.price)
            orders[0].save()
        else:
            orderprice = int(saved_fields['quantity']) * float(item.price)
            currentorder = Order(orderid=orderid, item=item, cart=currentcart, price=orderprice, **saved_fields)
            currentorder.save()
            
        user = User.objects.get(username=request.user.username)
        cart = user.cart
        listorders = Order.objects.filter(cart=cart).all()
        cart.totalprice = sum([o.price for o in listorders])
        cart.save()
        return redirect(request.META.get('HTTP_REFERER'))


@require_http_methods(["POST"])
@login_required
def removeorder(request, id):
    order = Order.objects.get(pk=id)
    order.delete()
    return redirect('dashboard:cart')

@require_http_methods(["POST"])
@login_required
def reviewitem(request, id):
    exclude_keys = ['csrfmiddlewaretoken']
    fields = {key: value for key, value in request.POST.items()}
    saved_fields = {k: fields[k] for k in set(list(fields.keys())) - set(exclude_keys)}
    user = User.objects.get(username=request.user.username)
    item = Item.objects.get(pk=id)
    review = Rating(item=item, user=user, **saved_fields)
    review.save()
    return redirect(request.META.get('HTTP_REFERER'))

    
def change_status():
    items = Item.objects.filter(quantity__gt=0).exclude(status='out of stock').all().order_by('?')[:10]
    options = ['default', 'sale']
    for i in items:
        i.status = rd.choice(options)
        i.save()

    

@register.filter
def ratesavg(rates):
    try:
        return sum([r.rate for r in rates]) // len(rates)
    except:
        return 0
        

@register.filter
def inrange(loop):
    return range(loop)

@register.filter
def diffrange(loop):
    return range(5-loop)

dashboard/templates/cart.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static './icons/favicon.png' %}" type="">

  <title> foodex: {% block title %}{% endblock %}</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static './dashboard/css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static './dashboard/css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static './dashboard/css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static './dashboard/css/responsive.css' %}" rel="stylesheet" />
  <link href="{% static './dashboard/css/cart.css' %}" rel="stylesheet" />
</head>


<body>
    <!-- header section strats -->
    <header class="bg-dark header_section">
        <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{% url 'dashboard:home' %}">
            <span>
                <img src="{% static 'favicon.png' %}" alt="">
                foodex
            </span>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav px-0  mr-auto  mr-auto ">

                <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard:menu' %}">Main Menu</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:menu' %}">Book Table</a>
                </li>
                {% endif %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard:about' %}">About</a>
                </li>
            </ul>
            <div class="user_option">
                <form class="flex d-flex justifiy-content form-inline my-2 my-lg-0" style="width: auto;">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                    <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                    </div>
                    <input class="form-control mr-sm-2" type="search" placeholder="search for.." aria-label="Search">
                </div>
                </form>
                {% if request.user.is_authenticated %}
                <div class="text-warning dropdown">
                <a for="menu-d" class="dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user" aria-hidden="true"></i>
                </a>
                <div id="menu-d" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'dashboard:cart' %}"><i class="fa fa-cart-plus"></i> my cart</a>
                    <a class="dropdown-item" href="{% url 'dashboard:watchlist' %}"><i class="fa fa-heart"></i> favourite</a>
                    <a class="dropdown-item" href="{% url 'users:profile' %}"><i class="fa fa-cog"></i> settings</a>
                    <a class="dropdown-item" href="{% url 'users:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> logout</a>
                </div>
                </div>
                {% else %}
                <a href="{% url 'users:login' %}" class="user_link">
                    <i class="fa fa-user" aria-hidden="true"></i>
                </a>
                {% endif %}

                <a href="{% url 'orders:orders' %}" class="order_online">
                Order Online
                </a>
            </div>
            </div>
        </nav>
        </div>
    <!-- end header section -->
    </header>

    <div class="mt-5 mb-5 container">
        {% include 'includes/message.html' %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-md-9">
                <div class="ibox">
                    <div class="ibox-title">
                        <span class="pull-right">(<strong>{{orders|length}}</strong>) items</span>
                        <h5>Items in your cart</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table shoping-cart-table">
                                <tbody>
                                {% for order in orders %}
                                    <tr>
                                        <td width="90">
                                            <div class="cart-product-imitation">
                                                <img style="width:100%;height:8vh;object-fit: contain;"  src="{{order.item.img}}" alt="">
                                            </div>
                                        </td>
                                        <td class="desc">
                                            <h3>
                                            <a href="{% url 'dashboard:item' order.item.id %}" class="text-navy">
                                                {{order.item.title}}
                                            </a>
                                            <small>{{order.orderid}}</small>
                                            </h3>
                                            <div class="m-t-sm">
                                                <span class="mr-1"><small>size: {{order.size}}</small></span>    
                                                <span class="ml-1"><small>type: {{order.type}}</small></span>
                                            </div>

                                            <div class="m-t-sm">
                                                <a href="#" class="text-muted"><i class="fa fa-gift"></i> Add gift package</a>
                                                |
                                                <a href="{% url 'orders:removeorder' order.id %}" class="text-muted"><i class="fa fa-trash"></i> Remove item</a>
                                            </div>
                                        </td>
                                        <td>
                                            Qty: {{order.quantity}}
                                            {% comment %} <s class="small text-muted">$230,00</s> {% endcomment %}
                                        </td>
        
                                        <td>
                                            ${{order.item.price}}
                                            
                                        </td>
        
                                        <td>
                                            {% comment %} <s class="small text-muted">$230,00</s> {% endcomment %}
                                            <h4>
                                                ${{order.price}}
                                                
                                            </h4>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                
                <div class="ibox-content">
                    
                    <a href="{% url 'dashboard:menu' %}"> <button class="btn btn-white"><i class="fa fa-arrow-left"></i> Continue shopping</button></a>

                </div>
            </div>
            </div>

            <div class="col-md-3">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Cart Summary</h5>
                    </div>
                    <div class="ibox-content">
                        <span>
                            Total
                        </span>
                        {% if cart.state %}
                            <h2 id="price" class="font-bold">
                                {{cart.totalprice}} <label class="text-danger text-sm">+25</label> $
                            </h2>
                        {% else %}
                        <h2 id="price" class="font-bold">
                            {{cart.totalprice}} $
                        </h2>
                        {% endif %}
                        <hr>
                        <span class="text-muted small">
                            *For all part of Egypt applicable sales tax will be applied
                        </span>
                        <div class="mx-auto mt-2 m-t-sm">
                            {% if request.user.card %}
                                {% if cart.state %}
                                    <form action="{% url 'orders:pay' %}" method="post"> {% csrf_token %}
                                        <div class="ml-1 form-group pull-right" style="margin:6px 10px 0 0">
                                            <input type="checkbox" class="form-check-input" id="paid" name="paid" value="upon receipt">
                                            <label class="form-check-label" for="paid">upon receipt</label>
                                            <script>
                                                check = document.querySelector('#paid');
                                                price = document.querySelector('#price');
                                                check.addEventListener('change', ()=> {
                                                    if (check.checked) {
                                                        alert('we kindly take delivery fees from your card')
                                                    } 
                                                });
                                            </script>
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-sm mb-2">Checkout</button>
                                    </form> 
                                {% else %}
                                <h4>you have not add items yet. <a href="{% url 'orders:orders' %}">Order Now!!</a><h4>

                                {% endif %}
                      
                            {% else %}
                                <h4>you have not add card yet. please click <a href="{% url 'users:profile' %}">here</a> to add one<h4>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
    
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Support</h5>
                    </div>
                    <div class="ibox-content text-center">
                        <h3><i class="fa fa-phone"></i> +201016909285</h3>
                        <span class="small">
                            Please contact with us if you have any questions. We are avalible 24h.
                        </span>
                    </div>
                </div>
 
<!-- jQery -->
<script src="{% static './dashboard/js/jquery-3.4.1.min.js' %}"></script>
<!-- popper js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<!-- bootstrap js -->
<script src="{% static './dashboard/js/bootstrap.js' %}"></script>
<!-- owl slider -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<!-- isotope js -->
<script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
<!-- nice select -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
<!-- custom js -->
<script src="{% static './dashboard/js/custom.js' %}"></script>
<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
</script>
<!-- End Google Map -->

</body>
</html>

dashboard/templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block title %} Homepage{% endblock %}


{% block main %}
{% include './includes/offers.html' %} 
{% include './includes/menu.html' %}
{% include './includes/clients.html' %}
{% endblock %}

dashboard/templates/menu.html
{% extends "layout.html" %}
{% load static %}
{% block title %} Menu{% endblock %}


{% block main %}
{% include './includes/menu.html' %}
{% endblock %}
